version: '3'

services:
  web:
    image: cascade 
    build: 
      context: .
      args:
        PORT: '80'
        # REDIS_URL: 'redis://10.0.0.19:6379/8' # asia-southeast1-a
        REDIS_URL: 'redis://10.0.0.3:6379/8' # europe-west1-b
        CLIENT_DIR: '../static/dist/cascade'
      dockerfile: Dockerfile
    command: python3 runcascade.py 
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
     - '8080:8080'
     - '8094:8094'
     - '80:80'
  workers:
    image: cascade 
    command: python3 runcascadeworker.py
    stdin_open: true
    tty: true
    volumes:
      - .:/app
