version: '3'

services:
  redis_db:
    image: redis:3.2-alpine
    volumes:
      - redis:/var/lib/redis/data
  web:
    image: cascade 
    build: 
      context: .
      args:
        PORT: '80'
        REDIS_URL: 'redis://redis_db:6379' 
        CLIENT_DIR: '../static/debug/cascade'
      dockerfile: Dockerfile
    command: python3 runcascade.py 
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
     - '8080:8080'
     - '8093:8093'
     - '80:80'
  workers:
    image: cascade 
    command: python3 runcascadeworker.py
    stdin_open: true
    tty: true
    volumes:
      - .:/app
volumes:
  redis: {}
