version: '3'

services:
  redis_db:
    image: redis:3.2-alpine
    volumes:
      - redis:/var/lib/redis/data
  web:
    image: cascade 
    build: 
      context: ..
      args:
        PORT: '80'
        REDIS_URL: 'redis://redis_db:6379' 
        CLIENT_DIR: '../dist/cascade'
      dockerfile: docker/Dockerfile
    command: python3.5 bin/server_cascade.py 
    stdin_open: true
    tty: true
    volumes:
      - ..:/app
    ports:
     - '8080:8080'
     - '8094:8094'
     - '80:80'
  workers:
    image: cascade 
    command: python3.5 bin/worker_cascade.py
    stdin_open: true
    tty: true
    volumes:
      - ..:/app
volumes:
  redis: {}
