version: '3'

services:
  redis_db:
    image: redis:3.2-alpine
    volumes:
      - redis:/var/lib/redis/data
  web:
    image: tb 
    build: 
      context: ..
      args:
        PORT: '80'
        REDIS_URL: 'redis://redis_db:6379' 
        CLIENT_DIR: '../dist/tb'
      dockerfile: docker/Dockerfile
    command: python3 bin/server_tb.py
    stdin_open: true
    tty: true
    volumes:
      - ..:/app
    ports:
     - '8080:8080'
     - '8093:8093'
     - '80:80'
  workers:
    image: tb 
    command: python3 bin/worker_tb.py
    stdin_open: true
    tty: true
    volumes:
      - ..:/app
volumes:
  redis: {}
