version: '3'

services:
  web:
    image: tb 
    build: 
      context: ..
      args:
        PORT: '80'
        # REDIS_URL: 'redis://10.0.0.19:6379/7' # asia-southeast1-a
        REDIS_URL: 'redis://10.0.0.3:6379/7' # europe-west1-b
        CLIENT_DIR: '../dist/tb'
        CMD: '(python3 runtbworker.py; python3 runtb.py) &'
      dockerfile: docker/Dockerfile
    command: python3 runtb.py 
    stdin_open: true
    tty: true
    volumes:
      - ..:/app
    ports:
     - '80:80'
